INSERT INTO CLIENTE (nombre, apellidos, email, create_at) VALUES ('Pedro', 'Puertas Rodríguez', 'pedropuertasr@gmail.com', '2023-05-22');
INSERT INTO CLIENTE (nombre, apellidos, email, create_at) VALUES ('María', 'Gómez Pérez', 'mariagomezp@gmail.com', '2023-06-15');
INSERT INTO CLIENTE (nombre, apellidos, email, create_at) VALUES ('Juan', 'López Fernández', 'juanl@correo.com', '2023-04-10');
INSERT INTO CLIENTE (nombre, apellidos, email, create_at) VALUES ('Laura', 'Martínez Sánchez', 'laurams@gmail.com', '2023-07-03');
INSERT INTO CLIENTE (nombre, apellidos, email, create_at) VALUES ('Carlos', 'Ramírez Vargas', 'carlosrv@correo.com', '2023-08-18');
INSERT INTO CLIENTE (nombre, apellidos, email, create_at) VALUES ('Ana', 'Hernández Gutiérrez', 'anahg@gmail.com', '2023-09-25');
INSERT INTO CLIENTE (nombre, apellidos, email, create_at) VALUES ('Luis', 'Torres López', 'luistorresl@gmail.com', '2023-05-12');
INSERT INTO CLIENTE (nombre, apellidos, email, create_at) VALUES ('Elena', 'García Rodríguez', 'elenagr@gmail.com', '2023-10-05');
INSERT INTO CLIENTE (nombre, apellidos, email, create_at) VALUES ('Sofía', 'Fernández Martínez', 'sofiafm@correo.com', '2023-07-19');